// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./components/common/Header.vue')['default']
    Congratulations: typeof import('./components/Congratulations.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    FormValidationIcon: typeof import('./components/form/validation/Icon.vue')['default']
    FormValidationMessage: typeof import('./components/form/validation/Message.vue')['default']
  }
}

export { }
